version: 5.0.4.{build}
image: Visual Studio 2017

branches:
  only:
    - master
configuration:
  - Coverage
  - Release
environment:
  PROJECT: toofz.NecroDancer
  MYGET_API_KEY:
    secure: XZmbJDCK5oiqhbLt1y7UXM6aCYPpF2tm/bJMUJzBsCe1fd2TuwXyaz99RN+bDpHw
notifications:
  - provider: Slack
    incoming_webhook:
      secure: c7l1UmXHWpIDLL1awU4r0QYVPToYM/XjV8trFyD1oHArKxs/vBTYiKYScr1EhCUgmEX6sAFBTvkUHF/k5B+cGjzqRBR2XkAO+lzk8cHQ1FI=
assembly_info:
  patch: true
  file: AssemblyInfo.cs
  assembly_version: $(appveyor_build_version)

init:
  - git config --global core.autocrlf input
install:
  - nuget update -Self
  - git clone https://github.com/leonard-thieu/toofz-build.git Scripts
  
before_build:
  - appveyor-retry nuget restore -Verbosity quiet
build:
  project: $(PROJECT).sln
  verbosity: minimal
  
test_script:
  - ps: |
      if ($env:CONFIGURATION -eq 'Coverage') {
        .\Scripts\Test-Project.ps1
      }
after_test:
  - ps: |
      if ($env:CONFIGURATION -eq 'Coverage') {
        .\Scripts\Submit-CodeCoverageResults.ps1
      }

deploy_script:
  - ps: |
      if ($env:CONFIGURATION -eq 'Release') {
        .\Scripts\Deploy-NuGetPackage.ps1
      }