version: $(VersionPrefix).{build}
image: Visual Studio 2017

skip_branch_with_pr: true
skip_commits:
  files:
    - LICENSE
    - README.md
configuration:
  - Release
environment:
  VersionPrefix: 0.0.0
  VersionSuffix: dev
  FileVersion: '%APPVEYOR_BUILD_VERSION%'
  PackageServerApiKey:
    secure: XZmbJDCK5oiqhbLt1y7UXM6aCYPpF2tm/bJMUJzBsCe1fd2TuwXyaz99RN+bDpHw
  
before_build:
  - nuget restore -Verbosity quiet
build:
  project: toofz.NecroDancer.sln
  verbosity: minimal

test_script:
  - ps: |
      $projectPath = Resolve-Path .\test\toofz.NecroDancer.Tests\toofz.NecroDancer.Tests.csproj
      msbuild $projectPath /nologo /verbosity:minimal /target:Test

deploy_script:
  - ps: |
      $projectPath = Resolve-Path .\src\toofz.NecroDancer\toofz.NecroDancer.csproj
      msbuild $projectPath /nologo /verbosity:minimal /target:Pack /property:PublishPackage=$env:APPVEYOR_REPO_TAG
