coverage:
  notify:
    slack:
      default:
        url: secret:SmcZ8BwDB1ISLzxwJUfbnF7+9FE/hJCIqu4zw93afY0FBa+F5DLHoy+6VF0Vj9e/Qu+xBKqNm4OFBfxTPNzR54PsnajvyYbIpOWbqkgkoCZg+XHhD2bsKkOuEqPrQ/ddc/8RVJEtbxX6mQd/oeeWYhOtBxxAsXM2LqbklK251fU=
        threshold: 1%
        only_pulls: false
        branches: null
        flags: null
        paths: null