//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace toofz.NecroDancer.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("toofz.NecroDancer.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] LocalCadenceWin {
            get {
                object obj = ResourceManager.GetObject("LocalCadenceWin", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;necrodancer&gt;
        ///  &lt;items&gt;
        ///    &lt;addchest_black levelEditor=&quot;False&quot; flyaway=&quot;|314|+1 BLACK CHEST PER RUN|&quot; hint=&quot;|314|+1 BLACK CHEST PER RUN|&quot; diamondCost=&quot;4&quot;&gt;addchest_black.png&lt;/addchest_black&gt;
        ///    &lt;addchest_red levelEditor=&quot;False&quot; flyaway=&quot;|315|+1 RED CHEST PER RUN|&quot; hint=&quot;|315|+1 RED CHEST PER RUN|&quot; diamondCost=&quot;1&quot;&gt;addchest_red.png&lt;/addchest_red&gt;
        ///    &lt;addchest_white levelEditor=&quot;False&quot; flyaway=&quot;|316|+1 PURPLE CHEST PER RUN|&quot; hint=&quot;|316|+1 PURPLE CHEST PER RUN|&quot; diamondCost=&quot;2&quot;&gt;addchest_white.png&lt;/addches [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NecroDancerData {
            get {
                return ResourceManager.GetString("NecroDancerData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;necrodancer&gt;
        ///  &lt;items&gt;
        ///    &lt;addchest_black levelEditor=&quot;False&quot; flyaway=&quot;|314|+1 BLACK CHEST PER RUN|&quot; hint=&quot;|314|+1 BLACK CHEST PER RUN|&quot; diamondCost=&quot;4&quot;&gt;addchest_black.png&lt;/addchest_black&gt;
        ///    &lt;addchest_red levelEditor=&quot;False&quot; flyaway=&quot;|315|+1 RED CHEST PER RUN|&quot; hint=&quot;|315|+1 RED CHEST PER RUN|&quot; diamondCost=&quot;1&quot;&gt;addchest_red.png&lt;/addchest_red&gt;
        ///    &lt;addchest_white levelEditor=&quot;False&quot; flyaway=&quot;|316|+1 PURPLE CHEST PER RUN|&quot; hint=&quot;|316|+1 PURPLE CHEST PER RUN|&quot; diamondCost=&quot;2&quot;&gt;addchest_white.png&lt;/addches [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string NecroDancerDataBaseline {
            get {
                return ResourceManager.GetString("NecroDancerDataBaseline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml?&gt;&lt;necrodancer cloudTimestamp=&quot;1437962524&quot;&gt;&lt;player addchest_blackUnlocked=&quot;true&quot; addchest_redUnlocked=&quot;true&quot; addchest_whiteUnlocked=&quot;true&quot; armor_chainmailUnlocked=&quot;true&quot; armor_giUnlocked=&quot;true&quot; armor_glassUnlocked=&quot;true&quot; armor_heavyplateUnlocked=&quot;true&quot; armor_obsidianUnlocked=&quot;true&quot; armor_platemailUnlocked=&quot;true&quot; bag_holdingUnlocked=&quot;true&quot; coins_x15Unlocked=&quot;false&quot; coins_x2Unlocked=&quot;false&quot; diamondDealerItems=&quot;&quot; diamondDealerSoldItem1=&quot;weapon_titanium_broadsword&quot; diamondDealerSoldItem2=&quot;food_2&quot; diamondDe [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SaveData {
            get {
                return ResourceManager.GetString("SaveData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml?&gt;&lt;necrodancer cloudTimestamp=&quot;1502975699&quot;&gt;&lt;player addchest_blackUnlocked=&quot;true&quot; addchest_redUnlocked=&quot;true&quot; addchest_whiteUnlocked=&quot;true&quot; armor_chainmailUnlocked=&quot;true&quot; armor_giUnlocked=&quot;true&quot; armor_glassUnlocked=&quot;true&quot; armor_heavyplateUnlocked=&quot;true&quot; armor_obsidianUnlocked=&quot;true&quot; armor_platemailUnlocked=&quot;true&quot; bag_holdingUnlocked=&quot;true&quot; coins_x15Unlocked=&quot;false&quot; coins_x2Unlocked=&quot;false&quot; diamondDealerItemsV2=&quot;&quot; diamondDealerSoldItemV2_1=&quot;weapon_blood_dagger&quot; diamondDealerSoldItemV2_2=&quot;food_2&quot; diamondD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SaveData_76561197960481221 {
            get {
                return ResourceManager.GetString("SaveData_76561197960481221", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml?&gt;&lt;necrodancer cloudTimestamp=&quot;1502618325&quot;&gt;&lt;player addchest_blackUnlocked=&quot;true&quot; addchest_redUnlocked=&quot;true&quot; addchest_whiteUnlocked=&quot;true&quot; armor_chainmailUnlocked=&quot;true&quot; armor_giUnlocked=&quot;true&quot; armor_glassUnlocked=&quot;true&quot; armor_heavyglassUnlocked=&quot;true&quot; armor_heavyplateUnlocked=&quot;true&quot; armor_obsidianCleaned=&quot;true&quot; armor_obsidianUnlocked=&quot;true&quot; armor_platemailUnlocked=&quot;true&quot; armor_quartzUnlocked=&quot;true&quot; bag_holdingUnlocked=&quot;true&quot; blood_drumUnlocked=&quot;true&quot; coins_x15Unlocked=&quot;true&quot; coins_x2Unlocked=&quot;true&quot; di [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SaveData_76561198074553183 {
            get {
                return ResourceManager.GetString("SaveData_76561198074553183", resourceCulture);
            }
        }
    }
}
